name = "BridgeDiffEq"
uuid = "1aa9af3a-2424-508f-bb7e-0626de155470"
version = "0.1.1"

[deps]
Bridge = "2d3116d5-4b8f-5680-861c-71f149790274"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Bridge = "0.10, 0.11"
DiffEqBase = "6"
Reexport = "0.2, 1"
StaticArrays = "0.10, 0.11, 0.12, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
